# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sha256/sha256.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256 || ORIG_REF_NAME==sha256} -quiet] -quiet

# IP: bd/sha256/ip/sha256_microblaze_0_0/sha256_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_microblaze_0_0 || ORIG_REF_NAME==sha256_microblaze_0_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_mdm_1_0/sha256_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_mdm_1_0 || ORIG_REF_NAME==sha256_mdm_1_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_clk_wiz_1_0/sha256_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_clk_wiz_1_0 || ORIG_REF_NAME==sha256_clk_wiz_1_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_rst_clk_wiz_1_100M_0/sha256_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==sha256_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_sha256_0_0/sha256_sha256_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_sha256_0_0 || ORIG_REF_NAME==sha256_sha256_0_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_microblaze_0_axi_periph_0/sha256_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_microblaze_0_axi_periph_0 || ORIG_REF_NAME==sha256_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_axi_intc_0_0/sha256_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_axi_intc_0_0 || ORIG_REF_NAME==sha256_axi_intc_0_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_axi_gpio_0_0/sha256_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_axi_gpio_0_0 || ORIG_REF_NAME==sha256_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_axi_uartlite_0_0/sha256_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_axi_uartlite_0_0 || ORIG_REF_NAME==sha256_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_xbar_0/sha256_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_xbar_0 || ORIG_REF_NAME==sha256_xbar_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_dlmb_v10_0/sha256_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_dlmb_v10_0 || ORIG_REF_NAME==sha256_dlmb_v10_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_ilmb_v10_0/sha256_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_ilmb_v10_0 || ORIG_REF_NAME==sha256_ilmb_v10_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_dlmb_bram_if_cntlr_0/sha256_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==sha256_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_ilmb_bram_if_cntlr_0/sha256_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==sha256_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_lmb_bram_0/sha256_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_lmb_bram_0 || ORIG_REF_NAME==sha256_lmb_bram_0} -quiet] -quiet

# IP: bd/sha256/ip/sha256_axi_gpio_1_0/sha256_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sha256_axi_gpio_1_0 || ORIG_REF_NAME==sha256_axi_gpio_1_0} -quiet] -quiet

# XDC: bd/sha256/sha256_ooc.xdc
