webtalk_init -webtalk_dir /media/ramalho/hddUnix/ECT/CR/Get-Shaded-256/teste/teste.sim/sim_1/behav/xsim/xsim.dir/sha_hw_simu_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 26 17:20:24 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174914471_178259212_210646180_906" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2751ae04-9c4e-4112-a5b0-85b506c8ca9b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e073687046754904acff0d64df96ed94" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2985.611 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "9900 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "136972_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1838516225 -regid "174914471_178259212_210646180_906" -xml /media/ramalho/hddUnix/ECT/CR/Get-Shaded-256/teste/teste.sim/sim_1/behav/xsim/xsim.dir/sha_hw_simu_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/ramalho/hddUnix/ECT/CR/Get-Shaded-256/teste/teste.sim/sim_1/behav/xsim/xsim.dir/sha_hw_simu_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/ramalho/hddUnix/ECT/CR/Get-Shaded-256/teste/teste.sim/sim_1/behav/xsim/xsim.dir/sha_hw_simu_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
